### ISSUE TITLE
private import across modules - check attributes as well?

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas-dev-flaker#21]
xref https://github.com/pandas-dev/pandas/pull/36144#issuecomment-817687375

**Comment by twoertwein** [comment]
Pyright can find those cases with these two flags:

reportPrivateUsage
reportPrivateImportUsage

See https://github.com/microsoft/pyright/blob/main/docs/configuration.md

**Comment by MarcoGorelli** [comment]
Oh, nice! So this one's OK to close? Doing so then

**Comment by twoertwein** [comment]
They aren't enabled yet because there are quite a few violations that need to be fixed first.
